// <auto-generated />
namespace dev.ShopTableApp.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addvirtualsho : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addvirtualsho));
        
        string IMigrationMetadata.Id
        {
            get { return "201709142003077_add virtual sho"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
